config/routes.rb
Rails.application.routes.draw do
  
  resources :project_types
  resources :work_diaries
  resources :bank_accounts
  resources :banks
  resources :tasks
  resources :task_types
  resources :stages
  
  resources :constructions do
    resources :tasks
    end 

  resources :construction_types
  resources :document_types
  
  resources :people do
    resources :employments    
  end
  
  resources :analyzes 
  resources :cities
  resources :countries
  resources :menu_items
  resources :phone_types
  resources :settings
  resources :states
  resources :users
  
  devise_for :users, path: 'u'

  post 'utils/postal_code'
  post 'utils/cities'
  get 'utils/cities'

  root 'constructions#index'
  mount Crono::Web, at: '/crono'
end

app/models/ability.rb
# frozen_string_literal: true

class Ability
  include CanCan::Ability

  def initialize(user)
    # Define abilities for the passed in user here. For example:
    #
    #   user ||= User.new # guest user (not logged in)
    #   if user.admin?
        can :manage, :all
    #   else
    #     can :read, :all
    #   end
    #
    # The first argument to `can` is the action you are giving the user
    # permission to do.
    # If you pass :manage it will apply to every action. Other common actions
    # here are :read, :create, :update and :destroy.
    #
    # The second argument is the resource the user can perform the action on.
    # If you pass :all it will apply to every resource. Otherwise pass a Ruby
    # class of the resource.
    #
    # The third argument is an optional hash of conditions to further filter the
    # objects.
    # For example, here the user can only update published articles.
    #
    #   can :update, Article, :published => true
    #
    # See the wiki for details:
    # https://github.com/CanCanCommunity/cancancan/wiki/Defining-Abilities
  end
end

app/models/address.rb
class Address < ApplicationRecord
  belongs_to :city
  belongs_to :addressable, polymorphic: true
end

app/models/bank.rb
class Bank < ApplicationRecord
end

app/models/bank_account.rb
class BankAccount < ApplicationRecord
  belongs_to :bank
  belongs_to :accountable, polymorphic: true
  
end

app/models/city.rb
class City < ApplicationRecord
  belongs_to :state
end

app/models/construction.rb
class Construction < ApplicationRecord
  
  enum pattern: {
        popular: 0,
        medium: 1,
        high: 2        
  } 
  
  monetize :expected_budget_cents
  
  belongs_to :construction_type
  
  has_many :addresses, dependent: :destroy, as: :addressable
  accepts_nested_attributes_for :addresses

  has_many :documents, dependent: :destroy, as: :documentable
  accepts_nested_attributes_for :documents

  has_many :tasks, dependent: :destroy
  accepts_nested_attributes_for :tasks


  has_many :projects, dependent: :destroy
  accepts_nested_attributes_for :projects

 

  def full_description
    "#{self.construction_type.name} - #{self.area} m²" 
  end

  after_create :create_tasks

  def create_tasks    

      self.construction_type.task_types.each do |tt|      
          puts "task type: "
          puts tt.name
          task = self.tasks.build
          task.status = "registered"
          task.task_type_id = tt.id
          self.save        
      end      
  end
  

end

app/models/country.rb
class Country < ApplicationRecord
end

app/models/document.rb
class Document < ApplicationRecord
  belongs_to :document_type
  #belongs_to :person

  belongs_to :documentable, polymorphic: true

  has_one_attached :attachment

end

app/models/menu_item.rb
class MenuItem < ApplicationRecord
  belongs_to :menu_item, optional: true
  has_many :menu_items, -> { order(position: :asc)}

  scope :published, -> { where(published: true, menu_item_id: nil).order(position: :asc) }
end

app/models/person.rb
class Person < ApplicationRecord
  has_ancestry

  has_one_attached :photo
  has_one :account

   # para cadastro dos dependentes nested
   belongs_to :person, inverse_of: :people, optional: true
   has_many :people, inverse_of: :person, dependent: :destroy
   accepts_nested_attributes_for :people, allow_destroy: true
   

  belongs_to :user, optional: true
  belongs_to :city
  belongs_to :place, optional: true
  #belongs_to :county, class_name: "City", foreign_key: "county_id", optional: true
  
  has_many :addresses, dependent: :destroy, as: :addressable
  has_many :phones, dependent: :destroy, as: :phonable
  
  has_many :documents, dependent: :destroy, as: :documentable
  accepts_nested_attributes_for :documents
  

  has_many :employments, dependent: :destroy
  accepts_nested_attributes_for :employments, allow_destroy: true

  accepts_nested_attributes_for :user, allow_destroy: true
  accepts_nested_attributes_for :addresses, allow_destroy: true
  accepts_nested_attributes_for :phones, allow_destroy: true

  validates :cpf, cpf: true
  validates :name, :rg, :birth, presence: true
  #validates :registration, :admission, :business_email, :place, presence: { unless: :person }
  validates :user, presence: { unless: :person }
 

  # para jogar dependentes no ancestry
  #before_save :set_parent_id
  


  def full_description
    "#{name} (CPF: #{cpf} )" 
  end


  def age
    now = Time.now.utc.to_date
    now.year - self.birth.year - (self.birth.to_date.change(:year => now.year) > now ? 1 : 0)
  end

 
end

app/models/phone.rb
class Phone < ApplicationRecord
  belongs_to :phone_type
  belongs_to :phonable, polymorphic: true
end
    

app/models/phone_type.rb
class PhoneType < ApplicationRecord
end

app/models/photo.rb
class Photo < ApplicationRecord
  belongs_to :work_diary
  
  has_one_attached :image, dependent: :destroy
end

app/models/project.rb
class Project < ApplicationRecord

  enum status: {
    initiated: 0,
    finished: 1        
  }  

  enum advice: {
    cau: 0,
    crea: 1        
  }  

  belongs_to :project_type
  belongs_to :state
  
  belongs_to :construction

  has_one_attached :attachment
end

app/models/project_type.rb
class ProjectType < ApplicationRecord
end

app/models/setting.rb
class Setting < ApplicationRecord
    monetize :fee_with_service_cents
    monetize :fee_without_service_cents
end

app/models/stage.rb
class Stage < ApplicationRecord
    has_many :task_types, dependent: :destroy
    accepts_nested_attributes_for :task_types, allow_destroy: true
end

app/models/state.rb
class State < ApplicationRecord
  belongs_to :country

  def name_with_state
    "#{name} - #{state&.acronym}"
  end
  
end

app/models/task.rb
class Task < ApplicationRecord

  enum status: {
    registered: 0,
    initiated: 1     
  } 

  belongs_to :task_type
  belongs_to :construction
  belongs_to :employment, optional: true

  monetize :budget_amount_cents
  monetize :cost_cents
  
end

app/models/task_type.rb
class TaskType < ApplicationRecord
  belongs_to :stage

  def full_description
    "Etapa: #{self.stage.name} - Tarefa: #{self.name}" 
  end

end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable, :trackable

  has_one :person
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  load_and_authorize_resource

  # GET /users
  def index
    params[:q][:s] = 'email asc' unless params[:q][:s]
    @q = User.ransack(params[:q])
    @users = @q.result(distinct: true).page(params[:page])
  end

  # GET /users/1
  def show
  end

  # GET /users/new
  def new
    @user = User.new
  end

  # GET /users/1/edit
  def edit
  end

  # POST /users
  def create
    @user = User.new(user_params)

    if @user.save
      redirect_to @user, notice: 'User was successfully created.'
    else
      render :new
    end
  end

  # PATCH/PUT /users/1
  def update
    if @user.update(user_params)
      redirect_to @user, notice: 'User was successfully updated.'
    else
      render :edit
    end
  end

  # DELETE /users/1
  def destroy
    @user.destroy
    redirect_to users_url, notice: 'User was successfully destroyed.'
  end

  private
    # Only allow a trusted parameter "white list" through.
    def user_params
      params.require(:user).permit(:email, :password)
    end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/_form.html.erb
<div class="card card-outline card-info">
  <%= simple_form_for(object) do |f| %>
    <div class="card-header">
      <h3 class="card-title">
        Dados do <%= object.class.model_name.human %>
        <%= link_to 'Cancelar', eval_with_rescue("#{controller_name}_path"), class: "btn btn-default btn-xs" %>
        <%= f.submit 'Salvar', class: "btn btn-info btn-xs" %>
      </h3>
    </div>
    <div class="card-body">
      <%= f.input :email %>
      <%= f.input :password %>
    </div>
    <div class="card-footer">
      <%= link_to 'Cancelar', eval_with_rescue("#{controller_name}_path"), class: "btn btn-default" %>

      <%= f.submit class: "btn btn-info" %>
    </div>
  <% end %>
</div>

app/views/users/edit.html.erb
<%= render 'form', object: @user %>

app/views/users/index.html.erb
<%= search_form_for @q, url: users_path do |f| %>
  <div class="card card-primary card-outline card-info">
    <div class="card-header with-border">
      <div class="row">
        <div class="col-md-12">
          <div class="input-group">
            <div class="input-group-btn">
              <button type="button" id='btn_filter' class="btn btn-info">
                <i class="fa fa-angle-right"></i>
                Filtrar
              </button>
            </div>
            <%= f.input :email_cont, label: false, required: false,
              placeholder: 'E-mail', wrapper: false %>
          </div>
        </div>
      </div>
      <div class="row">
        <div class="col-md-12 active-filters "></div>
      </div>
    </div>
    <div class="card-body" style='display: none;'>
      <div class="row">
      </div>
      <%= button_tag type: "submit", class: "btn btn-info" do %>
        <i class="fa fa-search"></i> Pesquisar
      <% end %>
    </div>
  </div>
<% end %>

<%= render 'shared/card_list',
  list: @users,
  sort_all: true,
  show_new: true,
  card_class: 'info',
  table_class: 'bootstrap-table-mobile',
  show_columns: [
    'id',
    'email'
  ]
%>

app/views/users/new.html.erb
<%= render 'form', object: @user %>

app/views/users/show.html.erb
<%= render 'shared/show', box_class: 'info', object: @user %>